.TH hfi1_eprom 8
'Copyright (C) 2014-2017. Intel Corporation. All rights reserved.
'This is not free software.
'Redistribution or modification is prohibited without the prior express
'written permission of Intel Corporation.
.SH NAME
hfi1_eprom \- Update/query images on the Intel Omni-Path HFI Adapter EPROM
.SH SYNOPSIS
.B hfi1_eprom
-u [loaderfile] [driverfile]
.br
.B hfi1_eprom
-V [-o][-c][-b]
.br
.B hfi1_eprom
-h
.br
.B hfi1_eprom
-h
.br
.SH DESCRIPTION
.P
.B hfi1_eprom
updates or queries images stored on the EPROM attached to Intel HFI adapters.
.P
The EPROM is divided into three named files: loader, config, and driver.
The loader file is the first 128 KiB of the EPROM and is visible to PCI
as an Option ROM.  The next 4 KiB is for link device configuration file.
The rest of the EPROM is the driver file.  Its size depends on the
SPI flash part used.  This tool will automatically determine the part size
based on the part device identifier.  Sizes will be 16, 32, 64, or 128 Mbits.
.P
EPROM updates will usually consist of an loader and driver file. The
config file is expected to be updated by OEMs for their specific hardware.
Config file update is allowed only in service mode.
.SH OPTIONS
.TP 14
.BI -u \ file(s)
Update files on EPROM. The tool will detect file type and write
it to correct EPROM file. Images not recognized as loader or driver will
be ignored.
.TP 14
.BI -V
Query version of files stored in the HFI adapter EPROM.
.TP 14
.BI -d \ device
Specifies the HFI device to use. By default the first detected HFI device will be used.
The -d option without device parameter will list all available HFI devices.
Without any parameters the -d  will list all available HFI devices.
You can select particular device by its index in device list
or device file /sys/bus/pci/devices/XXXXX/resource0.
Using "all" as a parameter to -d (-d all) will repeat operation on all available HFI devices.
.TP 14
.BI -v
Print more verbose messages.
.TP 14
.BI -h
Print a help message.
.TP 14
.BI -S
Enter service mode with additional options.
.SH EXAMPLES
.B hfi1_eprom
-d all -u /usr/share/opa/bios_images/*
.br
.B hfi1_eprom
-d all -V
.SH COPYRIGHT
Copyright (C) 2014-2017. Intel Corporation. All rights reserved.
.SH AUTHOR
Intel Corporation.
